spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost/backend
    username: postgres
    password: admin99#
---
app:
  token:
    secret: Dota2Secret2023
    issuer: Lw